#!/bin/bash
#
# setup-fprintd.sh — point fprintd at a freshly-built libfprint
#
# Writes /etc/systemd/system/fprintd.service.d/override.conf so the
# fprintd service loads libfprint-2.so from the user's build instead of
# the distro copy. Uses BindReadOnlyPaths= so fprintd's ProtectHome=yes
# sandbox stays intact — only the build directory becomes visible to
# the service.
#
# Usage:
#   sudo ./setup-fprintd.sh /path/to/libfprint/builddir
#
# The argument is the meson build directory (the parent of the
# libfprint/ subdir that contains libfprint-2.so.2.0.0).
#
# SPDX-License-Identifier: LGPL-2.1-or-later

set -euo pipefail

die () { echo "setup-fprintd: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must be run as root (try: sudo $0 ...)"
[ $# -eq 1 ] || die "usage: $0 /path/to/libfprint/builddir"

BUILD_DIR="$1"
[ -d "$BUILD_DIR" ] || die "build dir not found: $BUILD_DIR"

# Resolve to absolute, follow symlinks
BUILD_DIR="$(readlink -f -- "$BUILD_DIR")"
LIB_DIR="$BUILD_DIR/libfprint"

# Validate the build actually produced libfprint-2.so with the driver
[ -f "$LIB_DIR/libfprint-2.so.2.0.0" ] \
    || die "libfprint-2.so.2.0.0 not found in $LIB_DIR — did 'meson compile' run?"

if ! nm "$LIB_DIR/libfprint-2.so.2.0.0" 2>/dev/null \
        | grep -q "fpi_device_validity_0088_get_type"; then
    die "the libfprint at $LIB_DIR does not include the validity-0088 driver — \
re-run 'meson setup --wipe builddir -Ddrivers=validity_0088' and rebuild"
fi

# Check fprintd unit exists
systemctl cat fprintd.service >/dev/null 2>&1 \
    || die "fprintd.service is not installed on this system"

OVERRIDE_DIR=/etc/systemd/system/fprintd.service.d
OVERRIDE_FILE="$OVERRIDE_DIR/override.conf"

mkdir -p "$OVERRIDE_DIR"

# Use a stable destination OUTSIDE /home so it stays reachable under the
# fprintd unit's ProtectHome=yes sandbox.
EXPOSED=/run/libfprint-validity-0088

cat > "$OVERRIDE_FILE" <<EOF
# Generated by Kensington_VeriMark_06cb-0088/packaging/setup-fprintd.sh
# Points fprintd at the user-built libfprint that contains the validity-0088
# driver. BindReadOnlyPaths bind-mounts the build's lib directory to a path
# outside /home so fprintd's ProtectHome=yes sandbox doesn't hide it.
[Service]
Environment=LD_LIBRARY_PATH=$EXPOSED
BindReadOnlyPaths=$LIB_DIR:$EXPOSED
EOF

chmod 0644 "$OVERRIDE_FILE"

systemctl daemon-reload
systemctl restart fprintd.service

echo "setup-fprintd: wrote $OVERRIDE_FILE"
echo "setup-fprintd: fprintd restarted. Verify with:"
echo "    fprintd-list \"\$USER\""
echo "Expected: device 'Synaptics/Validity (pre-Prometheus)'."
